name: dcarnes
favicon: null
layout_spectrum: 0.3758286058437079
typography_spectrum: 0.30747768166475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6901303099002689
  lightness: 0.029530640225857496
  saturation: 0.5392714436165988
  rhythmicContrast: 0.8815132912714034
purpose: []
